EXPIRED_TIME_IN_MINUTES_KEY = "EXPIRED_TIME_IN_MINUTES"
DEFAULT_EXPIRED_TIME = 15


DEFAULT_HOST_KEY = "DEFAULT_HOST"
DEFAULT_HOST = "127.0.0.1"


DEFAULT_PORT_KEY = "DEFAULT_PORT"
DEFAULT_PORT = 8000
